### ISSUE TITLE
Разбор ответа АПИ (объекты на карте)

### ISSUE THREAD

**Issue by byaka** [byaka/WarThunderTacticalScreen_discuss#4]
https://github.com/byaka/WarThunderTacticalScreen_discuss/blob/master/API/mapObjects.js

непонятно, как задаются координаты и почему их по 2 пары на обьект.

**Comment by Telmer** [comment]
кто-то уже пытался разобраться. можно у них поспрашивать http://autoit-script.ru/index.php?topic=18197.0

**Comment by byaka** [comment]
там все закончилось на этапе разбора ответа с АПИ, собственно я тоже на этом остановился.
там ничего сложного быть не должно. я выдернул код клиента без библиотек, чисто отрисовка и интерфейса https://github.com/byaka/WarThunderTacticalScreen_discuss/blob/master/API/clientSource.js

**Comment by byaka** [comment]
итак. начнем с самолетов
для них передаются следующие координаты **x, y, dx, dy**
например

``` js
"dx": 0.988334,
"dy": 0.152305,
"x": 0.442905,
"y": 0.507544
```

**x** и **y** это координаты обьекта в относительных значениях
для преобразования их в абсолютные используется формула

```
 canvas.width*x*map_scale + map_pan_x
```

где **canvas.width** это размер холста, **map_scale** это коэффициент увеличения карты, **map_pan_x** это смещение видимой части карты (появляется при суме и позволяет перерисовывать только видимый фрагмент, а не всю ее целиком)

теперь что касается **dx** и **dy**. с ними интереснее. эти координаты задают угол поворота обьекта. по сути для самолетов это текущая траектория движения. кстати в клиенте эти значения для самолетов не используются, что собственно мы и видм на карте, обьекты всегда повернуты в одну сторону.

**Comment by byaka** [comment]
осталось состряпать тестовый пример чтобы проверить эти данные

**Comment by Telmer** [comment]
тогда непонятно почему dх и dy кривые....

предложение - по двум отсечкам времени и разности координат рисовать вектор и засечками обозначать положение самолета через 30, 60 секунд

**Comment by byaka** [comment]
всмысле кривые? почему они так сильно отличаются от x и y? думаю у них какойто хитрый алгоритм преобразования угла в координаты направления и в угоду производительности получмвшиеся координаты не опроксемируют. Но возможно я чтото не так понял. Надо делать пример, там будет видно.

> по двум отсечкам времени и разности координат рисовать вектор и засечками обозначать положение самолета через 30, 60 секунд

перенес в #5

**Comment by Telmer** [comment]
маркеры рисуются горизонтально. почему тогда dx и dy не 0, 0.5, 1 Или действительно хитрый алгоритм

**Comment by byaka** [comment]
непонял
dx и dy задают вторую точку вектора движения

**Comment by Telmer** [comment]
то есть это не угол наклона маркера?

**Comment by byaka** [comment]
под наклоном понимается поворот?
если так, то да. но угол задается не градусами или радеанами. угол задается смещением координат относительно оси X. Чтобы получить из такого угла нормальный угол поворота маркера, делается преобразование http://javascript.ru/math.atan2

**Comment by Telmer** [comment]
Своеобразно, ну да ладно

Надо бы архитектуру тестовых инструментов сразу продумать.

**Comment by byaka** [comment]
своеобразно - это мягко сказано:smile: я впервые вижу подобный способ передачи данных об обьектах для ДВУХМЕРНОЙ карты. есть предположение, что изначально там всеже планировалась трехмерная карта. жаль что ее нет, это была бы вещь!

насчет тестовых инструментов - большой плюс апи в том, что она передает корректные cors заголовки (ну вернее заголовки "разрешено с любого домена"). такчто теоретически тестовые примеры могут быть запущены откуда угодно.

с одной стороны было бы логично разместить их в сервисе типа jsfiddle чтобы иметь возможность налету править примеры ничего не скачивая. с другой - я жутко не люблю их редактор:smile:
про архитектуру незнаю даже, по мне дак чем примеры проще и короче - тем лучше.

**Comment by byaka** [comment]
итак, пример кода отрисовки карты
https://jsfiddle.net/BYaka/yr6uvsr1/

ВАЖНО. Поскольку jsfiddle работает по https, а апишка игры только по http, браузер будет ругаться, что протоколы не совпадают. Нужно разрешить несовпадение протоколов для данной страницы.
- В хроме это маленькая серая кнопка в виде щита в адресной строке.
- В лисе слева от адресной строки замочек с желтым восклицанием > стрелка "вправо" возле надписи "незащищенное соединение" > кнопка "временно отключить защиту"
